FROM openanalytics/r-ver:4.1.3

LABEL maintainer="M. Elise Lauterbur <lauterbur@gmail.com> for AAUW"

# system libraries of general use
RUN apt-get update && apt-get install --no-install-recommends -y \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

# system library dependency for the euler app
RUN apt-get update && apt-get install -y \
    libmpfr-dev libxml2 libxslt-dev \
    && rm -rf /var/lib/apt/lists/*

# basic shiny functionality
RUN R -q -e "install.packages(c('shiny', 'rmarkdown'))"

# install dependencies of the app
RUN R -q -e "install.packages(c('googlesheets4', 'tidyverse', 'ggplot2', 'scales', 'forcats', 'plyr'))"

# copy the app to the image
RUN mkdir /root/bio_analysis
COPY app /root/bio_analysis

COPY Rprofile.site /usr/local/lib/R/etc/

EXPOSE 3838

CMD ["R", "-q", "-e", "shiny::runApp('/root/bio_analysis')"]
